In [4]:
import pandas as pd

In [43]:
dataset = pd.read_csv("../data/hackernews.csv", 
                   encoding = "ISO-8859-1", 
                   names=['id', 'created_at', 'created_at_i', 'author', 'points', 'url_hostname', 'num_comments', 'title'])

In [44]:
dataset.head()

id                created_at  created_at_i        author  points  \
0  9079978  2015-02-20T11:29:58.000Z    1424431798    Immortalin       2   
1  9079983  2015-02-20T11:34:22.000Z    1424432062     Rutger24s       1   
2  9079986  2015-02-20T11:35:32.000Z    1424432132  AndrewDucker       3   
3  9079988  2015-02-20T11:36:18.000Z    1424432178     davidiach       1   
4  9080000  2015-02-20T11:41:06.000Z    1424432466       CiaranR       1   

          url_hostname  num_comments  \
0                  NaN             0   
1  startupjuncture.com             0   
2   blog.erratasec.com             0   
3          twitter.com             0   
4  phpconference.co.uk             0   

                                               title  
0       Ask HN: Simple SaaS as first Golang web app?  
1   24sessions: live business advice over video-chat  
2                            Some notes on SuperFish  
3    Apple Watch models could contain 29.16g of gold  
4  PHP UK Conference Diversity Scholarship Programme

In [45]:
len(dataset)

11004

In [46]:
dataset.drop(['id', 'created_at_i', 'author', 'num_comments'],inplace=True,axis=1)

In [47]:
dataset.head()

created_at  points         url_hostname  \
0  2015-02-20T11:29:58.000Z       2                  NaN   
1  2015-02-20T11:34:22.000Z       1  startupjuncture.com   
2  2015-02-20T11:35:32.000Z       3   blog.erratasec.com   
3  2015-02-20T11:36:18.000Z       1          twitter.com   
4  2015-02-20T11:41:06.000Z       1  phpconference.co.uk   

                                               title  
0       Ask HN: Simple SaaS as first Golang web app?  
1   24sessions: live business advice over video-chat  
2                            Some notes on SuperFish  
3    Apple Watch models could contain 29.16g of gold  
4  PHP UK Conference Diversity Scholarship Programme

In [48]:
dataset.rename(columns={'created_at': 'submission_time', 'url_hostname': 'url', 'points': 'upvotes', 'title': 'headline'}, inplace=True)

In [49]:
dataset.to_csv('../data/pre_process_hn.csv')

In [1]:
import re
import numpy
import random
from collections import Counter

In [14]:
headlines = [
    "PretzelBros, airbnb for people who like pretzels, raises $2 million",
    "Top 10 reasons why Go is better than whatever language you use.",
    "Why working at apple stole my soul (I still love it though)",
    "80 things I think you should do immediately if you use python.",
    "Show HN: carjack.me -- Uber meets GTA"
]

In [26]:
unique_words = list(set(" ".join(headlines).split(" ")))
def make_matrix(headlines, vocab):
    matrix = []
    for headline in headlines:
        counter = Counter(headline)
        row = [counter.get(w, 0) for w in vocab]
        matrix.append(row)
    df = pd.DataFrame(matrix)
    df.columns = unique_words
    return df
a = make_matrix(headlines, unique_words)
a

if  working  10  soul  airbnb  I  at  reasons  better  it  ...    Show  \
0   0        0   0     0       0  0   0        0       0   0  ...       0   
1   0        0   0     0       0  0   0        0       0   0  ...       0   
2   0        0   0     0       0  1   0        0       0   0  ...       0   
3   0        0   0     0       0  1   0        0       0   0  ...       0   
4   0        0   0     0       0  0   0        0       0   0  ...       0   

   than  80  Uber  HN:  should  is  Top  you  think  
0     0   0     0    0       0   0    0    0      0  
1     0   0     0    0       0   0    0    0      0  
2     0   0     0    0       0   0    0    0      0  
3     0   0     0    0       0   0    0    0      0  
4     0   0     0    0       0   0    0    0      0  

[5 rows x 51 columns]

In [27]:
new_headlines = [re.sub(r'[^\w\s\d]','',h.lower()) for h in headlines]
new_headlines = [re.sub("\s+", " ", h) for h in new_headlines]
unique_words = list(set(" ".join(new_headlines).split(" ")))
print(make_matrix(new_headlines, unique_words))

   if  working  2  10  carjackme  pretzels  soul  airbnb  at  go  ...    \
0   0        0  1   0          0         0     0       0   0   0  ...     
1   0        0  0   0          0         0     0       0   0   0  ...     
2   0        0  0   0          0         0     0       0   0   0  ...     
3   0        0  0   0          0         0     0       0   0   0  ...     
4   0        0  0   0          0         0     0       0   0   0  ...     

   raises  whatever  top  stole  than  80  should  is  you  think  
0       0         0    0      0     0   0       0   0    0      0  
1       0         0    0      0     0   0       0   0    0      0  
2       0         0    0      0     0   0       0   0    0      0  
3       0         0    0      0     0   0       0   0    0      0  
4       0         0    0      0     0   0       0   0    0      0  

[5 rows x 47 columns]


In [28]:
with open("../data/stop_words.txt", 'r') as f:
    stopwords = f.read().split("\n")

stopwords = [re.sub(r'[^\w\s\d]','',s.lower()) for s in stopwords]
unique_words = list(set(" ".join(new_headlines).split(" ")))
unique_words = [w for w in unique_words if w not in stopwords]
print(make_matrix(new_headlines, unique_words))

   working  2  10  carjackme  pretzels  soul  airbnb  reasons  better  \
0        0  1   0          0         0     0       0        0       0   
1        0  0   0          0         0     0       0        0       0   
2        0  0   0          0         0     0       0        0       0   
3        0  0   0          0         0     0       0        0       0   
4        0  0   0          0         0     0       0        0       0   

   pretzelbros  ...    love  language  immediately  million  uber  gta  \
0            0  ...       0         0            0        0     0    0   
1            0  ...       0         0            0        0     0    0   
2            0  ...       0         0            0        0     0    0   
3            0  ...       0         0            0        0     0    0   
4            0  ...       0         0            0        0     0    0   

   raises  stole  80  think  
0       0      0   0      0  
1       0      0   0      0  
2       0      0   0      

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(lowercase=True, stop_words="english")
matrix = vectorizer.fit_transform(headlines)
print(matrix.todense())

[[0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 1 1 0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1]
 [0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 1 0]
 [0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0]]


In [50]:
submissons = pd.read_csv("../data/pre_process_hn.csv", encoding = "ISO-8859-1")

In [51]:
# submissons['full_test'] = submissons['headline'] + " " + submissons['url']
full_matrix = vectorizer.fit_transform(submissons['headline'])
print(full_matrix.shape)

(11004, 13712)


In [52]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [54]:
col = submissons["upvotes"].copy(deep=True)
col_mean = col.mean()
col[col < col_mean] = 0
col[(col > 0) & (col > col_mean)] = 1

selector = SelectKBest(chi2, k=1000)
selector.fit(full_matrix, col)
top_words = selector.get_support().nonzero()

chi_matrix = full_matrix[:, top_words[0]]
chi_matrix

<11004x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 2147 stored elements in Compressed Sparse Row format>

In [65]:
transform_function = [
    lambda x: len(x),
    lambda x: x.count(" "),
    lambda x: x.count("."),
    lambda x: x.count("!"),
    lambda x: x.count("?"),
    lambda x: x.count(" ") / (x.count(".") + 1),
    lambda x: len(re.findall("\d", x)),
    lambda x: len(re.findall("[A-Z]", x)),
]

columns = []
for func in transform_function:
    columns.append(submissons["headline"].apply(func))
    
meta = numpy.asarray(columns).T
meta

array([[ 44.,   8.,   0., ...,   8.,   0.,   7.],
       [ 48.,   5.,   0., ...,   5.,   2.,   0.],
       [ 23.,   3.,   0., ...,   3.,   0.,   3.],
       ..., 
       [ 28.,   3.,   0., ...,   3.,   0.,   1.],
       [ 25.,   3.,   0., ...,   3.,   0.,   1.],
       [ 42.,   7.,   0., ...,   7.,   4.,   7.]])

In [66]:
columns = []

submissons_dates = pd.to_datetime(submissons['submission_time'])

transform_function = [
    lambda x: x.year,
    lambda x: x.month,
    lambda x: x.day,
    lambda x: x.hour,
    lambda x: x.minute,
]

for func in transform_function:
    columns.append(submissons_dates.apply(func))
    
non_nlp = numpy.asarray(columns).T

columns
# features = numpy.hstack([non_nlp, meta, chi_matrix.todense()])

[0        2015
 1        2015
 2        2015
 3        2015
 4        2015
 5        2015
 6        2015
 7        2015
 8        2015
 9        2015
 10       2015
 11       2015
 12       2015
 13       2015
 14       2015
 15       2015
 16       2015
 17       2015
 18       2015
 19       2015
 20       2015
 21       2015
 22       2015
 23       2015
 24       2015
 25       2015
 26       2015
 27       2015
 28       2015
 29       2015
          ... 
 10974    2015
 10975    2015
 10976    2015
 10977    2015
 10978    2015
 10979    2015
 10980    2015
 10981    2015
 10982    2015
 10983    2015
 10984    2015
 10985    2015
 10986    2015
 10987    2015
 10988    2015
 10989    2015
 10990    2015
 10991    2015
 10992    2015
 10993    2015
 10994    2015
 10995    2015
 10996    2015
 10997    2015
 10998    2015
 10999    2015
 11000    2015
 11001    2015
 11002    2015
 11003    2015
 Name: submission_time, dtype: int64, 0        2
 1        2
 2        2
 3        2


In [59]:
from sklearn.linear_model import Ridge

train_rows = 7500
random.seed()

indices = list(range(features.shape[0]))
random.shuffle(indices)

train = features[indices[:train_rows], :]
test = features[indices[train_rows:], :]
train_upvotes = submissons['upvotes'].iloc[indices[:train_rows]]
test_upvotes = submissons['upvotes'].iloc[indices[train_rows:]]
train = numpy.nan_to_num(train)

reg = Ridge(alpha = 0.1)
reg.fit(train, train_upvotes)
predictions = reg.predict(test)

In [60]:
print(sum(abs(predictions - test_upvotes)) / len(predictions))
average_upvotes = sum(test_upvotes)/len(test_upvotes)
print(sum(abs(average_upvotes - test_upvotes)) / len(predictions))

15.7181298388
17.0694468878


In [63]:
len(predictions)

3504